name = "ElderEmosServerPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54b36ad6786c3bef0848e4eec81ded3ed97814d21921fd77dbb11c5975f1ff50"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.38-beta"
